import Head from "next/head";
import Link from "next/link";
import styles from "../../styles/Home.module.css";
import ColorModeButton from "../../components/common/ColorMode";
import { Heading, Box } from "@chakra-ui/react";
import MultiSelectionTable from "../../components/MultiSelectionTable";
import VirtualizationTable from "../../components/VirtualizationTable"
import React, { useMemo, useEffect, useState, Component } from "react";

const Layout = ({children}:any) => {
  const [posts, setPosts] = useState([]);

  useEffect(() => {
    fetch('https://randomuser.me/api/?results=110')
      .then((res) => res.json())
      .then((result) => {
        setPosts(result);
      });
      console.log(posts);
  }, []);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.description}>
          <ColorModeButton />
          <Link href="/">
          <Heading>Home</Heading>
          </Link>
        </div>
        <Box
          display="flex"
          justifyContent="center"
          flexDirection="column"
          mt={8}
          w="40vw"
        >
            {children}
        </Box>
      </main>
    </>
  );
};

export default Layout;
