import Head from "next/head";
import Link from "next/link";
import styles from "../styles/Home.module.css";
import ColorModeButton from "../components/common/ColorMode";
import { Heading, Center, Box, Text } from "@chakra-ui/react";
import Table from "../components/table";

const Solution1 = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.description}>
          <ColorModeButton />
          <Link href="/">
          <Heading>Home</Heading>
          </Link>
        </div>
        <Box
          display="flex"
          justifyContent="center"
          flexDirection="column"
          mt={8}
          w="40vw"
        >
          <Table />
        </Box>
      </main>
    </>
  );
};

export default Solution1;
